# Generated by Django 2.2 on 2020-09-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='BlogPost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
