# Generated by Django 2.2 on 2020-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='testfiles'),
            preserve_default=False,
        ),
    ]
