# Generated by Django 2.2 on 2020-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0011_auto_20200926_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
